version: '3.8'

services:
  axis-imaging-api:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: axis-imaging-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - CLICKSEND_API_KEY=${CLICKSEND_API_KEY}
      - CLICKSEND_USERNAME=${CLICKSEND_USERNAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M