import { AppointmentStatus, ScanType, Priority } from '@prisma/client';
export interface AppointmentSeedData {
    appointmentNumber: string;
    patientNumber: string;
    scanType: ScanType;
    bodyPartExamined?: string;
    scheduledAt: Date;
    duration: number;
    status: AppointmentStatus;
    priority: Priority;
    referralNumber?: string;
    referringPhysician?: string;
    clinicalHistory?: string;
    room?: string;
    equipment?: string;
    contrastRequired: boolean;
    contrastAgent?: string;
    preparationInstructions?: string;
    interpreterRequired: boolean;
    interpreterLanguage?: string;
    wheelchairAccess: boolean;
    accompaniedByCaregiver: boolean;
    arrivedAt?: Date;
    startedAt?: Date;
    completedAt?: Date;
    checkedOutAt?: Date;
    scheduledBy?: string;
    performedBy?: string;
    notes?: string;
    patientInstructions?: string;
    specialInstructions?: string;
    reminderSent: boolean;
    confirmationSent: boolean;
    cancelledAt?: Date;
    cancelledBy?: string;
    cancellationReason?: string;
}
export declare const appointmentSeedData: AppointmentSeedData[];
export interface ReferralSeedData {
    referralNumber: string;
    referringGpProviderNumber: string;
    patientName: string;
    patientDob: Date;
    patientPhone: string;
    patientMedicare?: string;
    patientAddress?: string;
    scanType: ScanType;
    bodyPartExamined?: string;
    clinicalHistory: string;
    clinicalIndication?: string;
    previousImaging?: string;
    currentMedications?: string;
    relevantHistory?: string;
    priority: Priority;
    urgency: Priority;
    urgentReason?: string;
    medicareEligible: boolean;
    itemNumbers: string[];
    bulkBilled: boolean;
    referralDate: Date;
    expiryDate: Date;
    validUntilDate?: Date;
    documentUrl?: string;
    originalDocumentName?: string;
    isUsed: boolean;
    usedAt?: Date;
    isExpired: boolean;
    isVerified: boolean;
    verifiedBy?: string;
    verifiedAt?: Date;
}
export declare const referralSeedData: ReferralSeedData[];
export declare const appointmentStatusExamples: {
    SCHEDULED: string;
    CONFIRMED: string;
    IN_PROGRESS: string;
    COMPLETED: string;
    CANCELLED: string;
    NO_SHOW: string;
    RESCHEDULED: string;
};
export declare const preparationInstructions: {
    CT_CONTRAST: string;
    MRI_GENERAL: string;
    MRI_CONTRAST: string;
    ULTRASOUND_ABDOMINAL: string;
    ULTRASOUND_PELVIC: string;
    XRAY_GENERAL: string;
    MAMMOGRAPHY: string;
    NUCLEAR_MEDICINE: string;
};
//# sourceMappingURL=appointments.d.ts.map