"use strict";
// PostgreSQL seed data with proper enums and arrays
Object.defineProperty(exports, "__esModule", { value: true });
exports.referringGPSeedData = exports.patientSeedData = void 0;
const client_1 = require("@prisma/client");
exports.patientSeedData = [
    {
        user: {
            phoneNumber: '+61412345001',
            email: 'sarah.mitchell@email.com',
            firstName: 'Sarah',
            lastName: 'Mitchell',
            middleName: 'Jane',
            dateOfBirth: new Date('1985-03-15'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123456',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000001',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Michael Mitchell',
            emergencyContactPhone: '+61412345002',
            emergencyContactRelationship: 'Spouse',
        },
        patient: {
            patientNumber: 'AXI001001',
            mrn: 'MRN001001',
            streetAddress: '42 Collins Street',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654321',
            workPhone: '+61387654322',
            preferredContactMethod: client_1.ContactMethod.SMS,
            allergies: ['Shellfish', 'Iodine'],
            medicalConditions: ['Hypertension', 'Type 2 Diabetes'],
            currentMedications: ['Metformin 500mg BD', 'Amlodipine 5mg OD'],
            medicalHistory: {
                surgeries: ['Appendectomy 2010'],
                chronicConditions: ['Diabetes since 2018'],
                familyHistory: 'Father: Cardiac disease, Mother: Diabetes'
            },
            familyHistory: 'Father deceased from myocardial infarction age 65. Mother alive with type 2 diabetes.',
            socialHistory: 'Non-smoker, social drinker, office worker, exercises regularly',
            privateHealthInsurer: 'Medibank Private',
            privateHealthNumber: 'MP123456789',
            nextOfKinName: 'Michael Mitchell',
            nextOfKinPhone: '+61412345002',
            nextOfKinRelationship: 'Spouse',
            nextOfKinAddress: '42 Collins Street, Mickleham VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345003',
            email: 'james.thompson@email.com',
            firstName: 'James',
            lastName: 'Thompson',
            dateOfBirth: new Date('1978-11-22'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123457',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000002',
            dvaNumber: 'V123456',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Lisa Thompson',
            emergencyContactPhone: '+61412345004',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001002',
            mrn: 'MRN001002',
            streetAddress: '15 Smith Avenue',
            suburb: 'Craigieburn',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654323',
            preferredContactMethod: client_1.ContactMethod.EMAIL,
            allergies: ['Penicillin', 'Latex'],
            medicalConditions: ['Chronic back pain', 'Sleep apnea'],
            currentMedications: ['Paracetamol PRN', 'CPAP therapy'],
            medicalHistory: {
                surgeries: ['L4-L5 discectomy 2020'],
                chronicConditions: ['Chronic lower back pain'],
                workInjury: 'Work-related back injury 2019'
            },
            familyHistory: 'No significant family history',
            socialHistory: 'Ex-smoker (quit 2019), construction worker, limited mobility due to back condition',
            workersCompClaim: 'WC2019001234',
            nextOfKinName: 'Lisa Thompson',
            nextOfKinPhone: '+61412345004',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '15 Smith Avenue, Craigieburn VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: false,
        },
    },
    {
        user: {
            phoneNumber: '+61412345005',
            email: 'maria.rodriguez@email.com',
            firstName: 'Maria',
            lastName: 'Rodriguez',
            dateOfBirth: new Date('1992-07-08'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123458',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000003',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Spanish',
            emergencyContactName: 'Carlos Rodriguez',
            emergencyContactPhone: '+61412345006',
            emergencyContactRelationship: 'Father',
        },
        patient: {
            patientNumber: 'AXI001003',
            mrn: 'MRN001003',
            streetAddress: '78 Park Lane',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654324',
            preferredContactMethod: client_1.ContactMethod.SMS,
            allergies: [],
            medicalConditions: [],
            currentMedications: ['Oral contraceptive pill'],
            medicalHistory: {
                surgeries: [],
                chronicConditions: [],
                gynecological: 'Regular menstrual cycles, no complications'
            },
            familyHistory: 'Mother: Breast cancer age 55',
            socialHistory: 'Non-smoker, occasional alcohol, teacher, physically active',
            privateHealthInsurer: 'BUPA',
            privateHealthNumber: 'BP987654321',
            nextOfKinName: 'Carlos Rodriguez',
            nextOfKinPhone: '+61412345006',
            nextOfKinRelationship: 'Father',
            nextOfKinAddress: '78 Park Lane, Mickleham VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345007',
            email: 'robert.wilson@email.com',
            firstName: 'Robert',
            lastName: 'Wilson',
            dateOfBirth: new Date('1965-01-30'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123459',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000004',
            pensionNumber: 'P123456789',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Helen Wilson',
            emergencyContactPhone: '+61412345008',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001004',
            mrn: 'MRN001004',
            streetAddress: '123 Melbourne Road',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654325',
            preferredContactMethod: client_1.ContactMethod.PHONE,
            allergies: ['Aspirin'],
            medicalConditions: ['Atrial fibrillation', 'Osteoarthritis', 'Prostate enlargement'],
            currentMedications: ['Warfarin 5mg OD', 'Digoxin 0.25mg OD', 'Paracetamol PRN'],
            medicalHistory: {
                surgeries: ['TURP 2020'],
                chronicConditions: ['Atrial fibrillation since 2018', 'Osteoarthritis knees'],
                cardiac: 'AF well controlled on warfarin'
            },
            familyHistory: 'Father: Prostate cancer, Mother: Osteoporosis',
            socialHistory: 'Retired electrician, ex-smoker (30 pack years, quit 2015), minimal alcohol',
            nextOfKinName: 'Helen Wilson',
            nextOfKinPhone: '+61412345008',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '123 Melbourne Road, Mickleham VIC 3064',
            allowSmsReminders: false,
            allowEmailReminders: true,
            allowPostalMail: true,
            shareWithFamilyGp: true,
            allowResearch: false,
        },
    },
    {
        user: {
            phoneNumber: '+61412345009',
            email: 'jennifer.brown@email.com',
            firstName: 'Jennifer',
            lastName: 'Brown',
            dateOfBirth: new Date('1988-09-12'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123460',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000005',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'David Brown',
            emergencyContactPhone: '+61412345010',
            emergencyContactRelationship: 'Husband',
        },
        patient: {
            patientNumber: 'AXI001005',
            mrn: 'MRN001005',
            streetAddress: '56 Eucalyptus Drive',
            suburb: 'Craigieburn',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654326',
            workPhone: '+61387654327',
            preferredContactMethod: client_1.ContactMethod.EMAIL,
            allergies: ['Morphine', 'Codeine'],
            medicalConditions: ['Migraine', 'IBS'],
            currentMedications: ['Sumatriptan PRN', 'Probiotics'],
            medicalHistory: {
                surgeries: [],
                chronicConditions: ['Chronic migraine', 'Irritable bowel syndrome'],
                obstetric: 'G2P2, normal vaginal deliveries'
            },
            familyHistory: 'Sister: Migraine, Mother: Depression',
            socialHistory: 'Non-smoker, rare alcohol, nurse, shift worker',
            privateHealthInsurer: 'HCF',
            privateHealthNumber: 'HCF456789123',
            nextOfKinName: 'David Brown',
            nextOfKinPhone: '+61412345010',
            nextOfKinRelationship: 'Husband',
            nextOfKinAddress: '56 Eucalyptus Drive, Craigieburn VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345011',
            email: 'william.davis@email.com',
            firstName: 'William',
            lastName: 'Davis',
            middleName: 'John',
            dateOfBirth: new Date('1955-12-03'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123461',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000006',
            dvaNumber: 'V789012',
            pensionNumber: 'P987654321',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Margaret Davis',
            emergencyContactPhone: '+61412345012',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001006',
            mrn: 'MRN001006',
            streetAddress: '89 Veterans Way',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654328',
            preferredContactMethod: client_1.ContactMethod.PHONE,
            allergies: [],
            medicalConditions: ['PTSD', 'Chronic kidney disease', 'Hypertension'],
            currentMedications: ['Sertraline 50mg OD', 'Perindopril 4mg OD', 'Furosemide 20mg OD'],
            medicalHistory: {
                surgeries: ['Right knee replacement 2018'],
                chronicConditions: ['PTSD', 'CKD Stage 3', 'Essential hypertension'],
                military: 'Vietnam War veteran, Agent Orange exposure'
            },
            familyHistory: 'Father: Kidney disease, Brother: PTSD',
            socialHistory: 'Vietnam War veteran, ex-smoker (quit 1990), minimal alcohol, retired',
            nextOfKinName: 'Margaret Davis',
            nextOfKinPhone: '+61412345012',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '89 Veterans Way, Mickleham VIC 3064',
            allowSmsReminders: false,
            allowEmailReminders: false,
            allowPostalMail: true,
            shareWithFamilyGp: true,
            allowResearch: false,
        },
    },
    {
        user: {
            phoneNumber: '+61412345013',
            email: 'lisa.anderson@email.com',
            firstName: 'Lisa',
            lastName: 'Anderson',
            dateOfBirth: new Date('1995-05-20'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123462',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000007',
            healthcareCardNumber: 'HC123456789',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Susan Anderson',
            emergencyContactPhone: '+61412345014',
            emergencyContactRelationship: 'Mother',
        },
        patient: {
            patientNumber: 'AXI001007',
            mrn: 'MRN001007',
            streetAddress: '34 Student Street',
            suburb: 'Craigieburn',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654329',
            preferredContactMethod: client_1.ContactMethod.SMS,
            allergies: [],
            medicalConditions: ['Asthma', 'Anxiety'],
            currentMedications: ['Ventolin inhaler PRN', 'Sertraline 25mg OD'],
            medicalHistory: {
                surgeries: [],
                chronicConditions: ['Mild asthma', 'Generalized anxiety disorder'],
                psychiatric: 'GAD diagnosed 2020, responds well to SSRI'
            },
            familyHistory: 'Mother: Asthma, Father: Depression',
            socialHistory: 'University student, non-smoker, occasional alcohol, part-time retail worker',
            nextOfKinName: 'Susan Anderson',
            nextOfKinPhone: '+61412345014',
            nextOfKinRelationship: 'Mother',
            nextOfKinAddress: '78 Family Avenue, Craigieburn VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345015',
            email: 'antonio.giuseppe@email.com',
            firstName: 'Antonio',
            lastName: 'Giuseppe',
            dateOfBirth: new Date('1949-04-15'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123463',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000008',
            pensionNumber: 'P456789123',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Italian',
            emergencyContactName: 'Francesca Giuseppe',
            emergencyContactPhone: '+61412345016',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001008',
            mrn: 'MRN001008',
            streetAddress: '67 Roma Street',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654330',
            preferredContactMethod: client_1.ContactMethod.PHONE,
            allergies: ['Sulfonamides'],
            medicalConditions: ['Type 2 Diabetes', 'COPD', 'Peripheral vascular disease'],
            currentMedications: ['Metformin 1000mg BD', 'Tiotropium inhaler OD', 'Aspirin 100mg OD'],
            medicalHistory: {
                surgeries: ['Right below-knee amputation 2019'],
                chronicConditions: ['T2DM', 'COPD Gold Stage 2', 'PVD'],
                smoking: '60 pack year history, quit 2018'
            },
            familyHistory: 'Father: Diabetes, Mother: Heart disease',
            socialHistory: 'Retired factory worker, ex-smoker (60 pack years), prosthetic right leg',
            nextOfKinName: 'Francesca Giuseppe',
            nextOfKinPhone: '+61412345016',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '67 Roma Street, Mickleham VIC 3064',
            allowSmsReminders: false,
            allowEmailReminders: false,
            allowPostalMail: true,
            shareWithFamilyGp: true,
            allowResearch: false,
        },
    },
    {
        user: {
            phoneNumber: '+61412345017',
            email: 'emily.clark@email.com',
            firstName: 'Emily',
            lastName: 'Clark',
            dateOfBirth: new Date('1990-10-08'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123464',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000009',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Australian',
            emergencyContactName: 'Thomas Clark',
            emergencyContactPhone: '+61412345018',
            emergencyContactRelationship: 'Partner',
        },
        patient: {
            patientNumber: 'AXI001009',
            mrn: 'MRN001009',
            streetAddress: '91 Innovation Boulevard',
            suburb: 'Craigieburn',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654331',
            workPhone: '+61387654332',
            preferredContactMethod: client_1.ContactMethod.EMAIL,
            allergies: ['Contrast dye (mild reaction)'],
            medicalConditions: ['Hypothyroidism'],
            currentMedications: ['Levothyroxine 50mcg OD'],
            medicalHistory: {
                surgeries: [],
                chronicConditions: ['Hypothyroidism'],
                endocrine: 'TSH well controlled on thyroxine replacement'
            },
            familyHistory: 'Mother: Thyroid disease, Grandmother: Thyroid cancer',
            socialHistory: 'Software developer, non-smoker, occasional alcohol, yoga practitioner',
            privateHealthInsurer: 'NIB',
            privateHealthNumber: 'NIB321654987',
            nextOfKinName: 'Thomas Clark',
            nextOfKinPhone: '+61412345018',
            nextOfKinRelationship: 'Partner',
            nextOfKinAddress: '91 Innovation Boulevard, Craigieburn VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345019',
            email: 'mohammed.hassan@email.com',
            firstName: 'Mohammed',
            lastName: 'Hassan',
            dateOfBirth: new Date('1975-08-25'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123465',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000010',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Lebanese',
            emergencyContactName: 'Fatima Hassan',
            emergencyContactPhone: '+61412345020',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001010',
            mrn: 'MRN001010',
            streetAddress: '45 Harmony Avenue',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654333',
            workPhone: '+61387654334',
            preferredContactMethod: client_1.ContactMethod.SMS,
            allergies: [],
            medicalConditions: ['Gout', 'Fatty liver disease'],
            currentMedications: ['Allopurinol 300mg OD'],
            medicalHistory: {
                surgeries: [],
                chronicConditions: ['Recurrent gout', 'NAFLD'],
                metabolic: 'NAFLD diagnosed on ultrasound 2021'
            },
            familyHistory: 'Father: Gout, Mother: Diabetes',
            socialHistory: 'Restaurant owner, non-smoker, occasional alcohol, extended family support',
            nextOfKinName: 'Fatima Hassan',
            nextOfKinPhone: '+61412345020',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '45 Harmony Avenue, Mickleham VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345021',
            email: 'grace.wong@email.com',
            firstName: 'Grace',
            lastName: 'Wong',
            dateOfBirth: new Date('1998-02-14'),
            gender: client_1.Gender.FEMALE,
            medicareNumber: '2428123466',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000011',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Chinese',
            emergencyContactName: 'Helen Wong',
            emergencyContactPhone: '+61412345022',
            emergencyContactRelationship: 'Mother',
        },
        patient: {
            patientNumber: 'AXI001011',
            mrn: 'MRN001011',
            streetAddress: '22 Golden Way',
            suburb: 'Craigieburn',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654335',
            preferredContactMethod: client_1.ContactMethod.EMAIL,
            allergies: [],
            medicalConditions: [],
            currentMedications: [],
            medicalHistory: {
                surgeries: [],
                chronicConditions: [],
                general: 'Generally healthy young adult'
            },
            familyHistory: 'No significant family history',
            socialHistory: 'University student studying medicine, non-smoker, no alcohol, lives with parents',
            nextOfKinName: 'Helen Wong',
            nextOfKinPhone: '+61412345022',
            nextOfKinRelationship: 'Mother',
            nextOfKinAddress: '22 Golden Way, Craigieburn VIC 3064',
            allowSmsReminders: true,
            allowEmailReminders: true,
            allowPostalMail: false,
            shareWithFamilyGp: true,
            allowResearch: true,
        },
    },
    {
        user: {
            phoneNumber: '+61412345023',
            email: 'peter.kowalski@email.com',
            firstName: 'Peter',
            lastName: 'Kowalski',
            dateOfBirth: new Date('1962-06-18'),
            gender: client_1.Gender.MALE,
            medicareNumber: '2428123467',
            medicareExpiryDate: new Date('2025-12-31'),
            ihiNumber: '8003608000000012',
            role: client_1.UserRole.PATIENT,
            culturalBackground: 'Polish',
            emergencyContactName: 'Anna Kowalski',
            emergencyContactPhone: '+61412345024',
            emergencyContactRelationship: 'Wife',
        },
        patient: {
            patientNumber: 'AXI001012',
            mrn: 'MRN001012',
            streetAddress: '111 Europa Drive',
            suburb: 'Mickleham',
            state: client_1.AustralianState.VIC,
            postcode: '3064',
            country: 'Australia',
            homePhone: '+61387654336',
            preferredContactMethod: client_1.ContactMethod.PHONE,
            allergies: ['Bee stings (anaphylaxis)'],
            medicalConditions: ['Coronary artery disease', 'Dyslipidemia'],
            currentMedications: ['Atorvastatin 40mg ON', 'Metoprolol 50mg BD', 'Aspirin 100mg OD', 'Clopidogrel 75mg OD'],
            medicalHistory: {
                surgeries: ['CABG x3 2020', 'Cholecystectomy 2015'],
                chronicConditions: ['Triple vessel CAD', 'Hyperlipidemia'],
                cardiac: 'CABG 2020, good functional recovery'
            },
            familyHistory: 'Father: MI age 58, Brother: CAD',
            socialHistory: 'Retired plumber, ex-smoker (40 pack years, quit 2019), EpiPen carried',
            nextOfKinName: 'Anna Kowalski',
            nextOfKinPhone: '+61412345024',
            nextOfKinRelationship: 'Wife',
            nextOfKinAddress: '111 Europa Drive, Mickleham VIC 3064',
            allowSmsReminders: false,
            allowEmailReminders: true,
            allowPostalMail: true,
            shareWithFamilyGp: true,
            allowResearch: false,
        },
    }
];
exports.referringGPSeedData = [
    {
        firstName: 'David',
        lastName: 'Peterson',
        title: 'Dr',
        practiceName: 'Mickleham Medical Centre',
        providerNumber: '123456AU',
        prescriberId: 'PRS123456',
        ahpraNumber: 'MED0001234567',
        phoneNumber: '+61387651001',
        faxNumber: '+61387651002',
        email: 'david.peterson@micklehammedical.com.au',
        streetAddress: '50 Mickleham Drive',
        suburb: 'Mickleham',
        state: client_1.AustralianState.VIC,
        postcode: '3064',
        specializations: ['General Practice', 'Family Medicine'],
        preferredContactMethod: client_1.ContactMethod.EMAIL,
    },
    {
        firstName: 'Sarah',
        lastName: 'Johnson',
        title: 'Dr',
        practiceName: 'Craigieburn Family Practice',
        providerNumber: '234567AU',
        prescriberId: 'PRS234567',
        ahpraNumber: 'MED0001234568',
        phoneNumber: '+61387651003',
        faxNumber: '+61387651004',
        email: 'sarah.johnson@craigieburn.med.au',
        streetAddress: '88 Central Park Avenue',
        suburb: 'Craigieburn',
        state: client_1.AustralianState.VIC,
        postcode: '3064',
        specializations: ['General Practice', 'Women\'s Health'],
        preferredContactMethod: client_1.ContactMethod.EMAIL,
    },
    {
        firstName: 'Michael',
        lastName: 'Chen',
        title: 'Dr',
        practiceName: 'Northern Suburbs Medical',
        providerNumber: '345678AU',
        prescriberId: 'PRS345678',
        ahpraNumber: 'MED0001234569',
        phoneNumber: '+61387651005',
        faxNumber: '+61387651006',
        email: 'michael.chen@northernsuburbs.med.au',
        streetAddress: '22 Health Street',
        suburb: 'Craigieburn',
        state: client_1.AustralianState.VIC,
        postcode: '3064',
        specializations: ['General Practice', 'Chronic Disease Management'],
        preferredContactMethod: client_1.ContactMethod.EMAIL,
    },
    {
        firstName: 'Emma',
        lastName: 'Williams',
        title: 'Dr',
        practiceName: 'Hume Healthcare',
        providerNumber: '456789AU',
        prescriberId: 'PRS456789',
        ahpraNumber: 'MED0001234570',
        phoneNumber: '+61387651007',
        faxNumber: '+61387651008',
        email: 'emma.williams@humehealthcare.com.au',
        streetAddress: '156 Hume Highway',
        suburb: 'Craigieburn',
        state: client_1.AustralianState.VIC,
        postcode: '3064',
        specializations: ['General Practice', 'Mental Health'],
        preferredContactMethod: client_1.ContactMethod.EMAIL,
    },
    {
        firstName: 'Robert',
        lastName: 'Taylor',
        title: 'Dr',
        practiceName: 'Broadmeadows Medical Group',
        providerNumber: '567890AU',
        prescriberId: 'PRS567890',
        ahpraNumber: 'MED0001234571',
        phoneNumber: '+61387651009',
        faxNumber: '+61387651010',
        email: 'robert.taylor@broadmeadows.med.au',
        streetAddress: '45 Broadmeadows Drive',
        suburb: 'Broadmeadows',
        state: client_1.AustralianState.VIC,
        postcode: '3047',
        specializations: ['General Practice', 'Geriatric Medicine'],
        preferredContactMethod: client_1.ContactMethod.PHONE,
    }
];
//# sourceMappingURL=patients.js.map